### ISSUE TITLE
Software review

### ISSUE THREAD

**Issue by athy9193** [UBC-MDS/rhousehunter#21]

**Comment by elina-linglin** [comment]
Hi team,

Here are the links to software reviews for the R and Python versions of our package. Please provide feedback! 

R: https://github.com/UBC-MDS/software-review-2021/issues/23
Python: https://github.com/UBC-MDS/software-review-2021/issues/24

**Comment by elabandari** [comment]
Thank you so much for spearheading this! Looks great. Once Alex has the documentation PR merged feel free to update the description and we should be good to go!

**Comment by JuntingHe** [comment]
Hi Elina，

Thanks for your hard and it looks nice to me.

**Comment by athy9193** [comment]
Thank you @elina-linglin! The code-review submission looks great. Echoing reminder from Ela, too.
