### ISSUE TITLE
Function 4 : Emailer 

### ISSUE THREAD

**Issue by JuntingHe** [UBC-MDS/rhousehunter#8]
A function to email search results.

**Comment by elabandari** [comment]
A note about this function: rJava is a dependency that may be tricky to get running. 

To get rJava you need to install java (jdk8) from https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

And then run the following command `sudo R CMD javareconf`

**Comment by elabandari** [comment]
Function and tests merged with Pull Request #13
